FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App

# Copy everything
COPY AcademicVisitServer.sln ./
COPY AcademicVisitServer/*.csproj ./AcademicVisitServer/
COPY AcademicVisit.Data/*.csproj ./AcademicVisit.Data/

# Restore as distinct layers
RUN dotnet restore
# Copy everything else and build
COPY . ./
# Build and publish a release
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "AcademicVisitServer.dll"]